server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts: {}
  host: 0.0.0.0:25566
  max_players: 1000
  motd: ''
  ping_passthrough: false
  priorities:
  - hub_anarchy
  proxy_protocol: false
  query_enabled: true
  query_port: 25566
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 64
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: false
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: 1000
ip_forward: true
groups: {}
remote_ping_timeout: 5000
connection_throttle: -1
log_commands: true
stats: 72bae778-dbc8-49d0-a94a-d6bd90daf0a0
online_mode: false
forge_support: true
disabled_commands:
- disabledcommandhere
servers:
  anarchy:
    address: 10.0.1.11:25501
    motd: ''
    restricted: false
  crazy_anarchy:
    address: 10.0.1.11:25503
    motd: ''
    restricted: false
  creative_anarchy:
    address: 10.0.1.11:25502
    motd: ''
    restricted: false
  hub_anarchy:
    address: 10.0.1.11:25500
    motd: ''
    restricted: false
